"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SET_HOMEMENUS = exports.DELETE_SEARCH_CATE = exports.ADD_SEARCH_CATE = exports.SET_SEARCH_SITES_VALUE = exports.SET_SITES_PAGE = exports.SET_SITES_CATEGORY = exports.SET_CATEGORIES = exports.CHANGE_CURRENT_ITEM = exports.CHANGE_WEB_INFO = exports.EDIT_DRAWER_VISIBLE = exports.CHANGE_IS_EDIT = exports.SET_LOADING = exports.DIS_AUTO_LOAD = exports.AFTER_CHANGE = exports.DELETE_ONE_SITE = exports.ADD_ONE_SITE = exports.CLOSE_CUSTOM_ENGINE = exports.OPEN_CUSTOM_ENGINE = exports.DELETE_CUSTOME_ENGINE = exports.ADD_CUSTOM_ENGINE = exports.CHANGE_CURRENT_ENGINE = exports.CLOSE_ENGINE_POPOVER = exports.OPEN_ENGINE_POPOVER = exports.ADD_CHOOSE_ENGINE = exports.DELETE_CHOOSE_ENGINE = exports.SET_WALLPAPER = exports.SET_WALLPAPERLOADING = exports.RESET_ALL = exports.SET_FONTCOLOR = exports.SET_FONTSIZE = exports.SET_SEARCHBAROPACITY = exports.SET_SEARCHBARSIZE = exports.SET_SEARCHBARRADIUS = exports.HIDE_SEARCHTYPE = exports.HIDE_SEARCHBAR = exports.SET_ICONSIZE = exports.SET_ICONRADIUS = exports.HIDE_ALLICONS = exports.SET_LAYOUT = exports.SET_HOMEBTN = exports.SET_NEWTYPE = exports.SET_CLOUDSAVE = exports.SET_BGBLUR = exports.SET_BGMASKOPACITY = exports.SET_BGSRC = exports.SET_SETTINGVIS = exports.setLogRegModalVis = exports.SET_BMHIS = exports.SET_SYSBARVIS = void 0;
// home 页的mutation
var SET_SYSBARVIS = 'SET_SYSBARVIS'; // 打开主添加面板

exports.SET_SYSBARVIS = SET_SYSBARVIS;
var SET_BMHIS = 'SET_BMHIS'; // 打开书签和历史记录
// user 的mutation

exports.SET_BMHIS = SET_BMHIS;
var setLogRegModalVis = 'setLogRegModalVis'; // 登录mutation
// setting 的mutation

exports.setLogRegModalVis = setLogRegModalVis;
var SET_SETTINGVIS = 'SET_SETTINGVIS'; // 打开设置面板

exports.SET_SETTINGVIS = SET_SETTINGVIS;
var SET_BGSRC = 'SET_BGSRC'; // 更换壁纸源

exports.SET_BGSRC = SET_BGSRC;
var SET_BGMASKOPACITY = 'SET_BGMASKOPACITY'; // 调节壁纸蒙版透明度

exports.SET_BGMASKOPACITY = SET_BGMASKOPACITY;
var SET_BGBLUR = 'SET_BGBLUR'; // 调节壁纸模糊度

exports.SET_BGBLUR = SET_BGBLUR;
var SET_CLOUDSAVE = 'SET_CLOUDSAVE'; // 调节壁纸模糊度

exports.SET_CLOUDSAVE = SET_CLOUDSAVE;
var SET_NEWTYPE = 'SET_NEWTYPE'; // 调节打开各类型内容的方式

exports.SET_NEWTYPE = SET_NEWTYPE;
var SET_HOMEBTN = 'SET_HOMEBTN'; // 调节主页各按钮是否显示

exports.SET_HOMEBTN = SET_HOMEBTN;
var SET_LAYOUT = 'SET_LAYOUT'; // 调节主页各图标布局

exports.SET_LAYOUT = SET_LAYOUT;
var HIDE_ALLICONS = 'HIDE_ALLICONS'; // 隐藏所有图标

exports.HIDE_ALLICONS = HIDE_ALLICONS;
var SET_ICONRADIUS = 'SET_ICONRADIUS'; // 调节图标圆角弧度

exports.SET_ICONRADIUS = SET_ICONRADIUS;
var SET_ICONSIZE = 'SET_ICONSIZE'; // 调节图标大小

exports.SET_ICONSIZE = SET_ICONSIZE;
var HIDE_SEARCHBAR = 'HIDE_SEARCHBAR'; // 是否隐藏搜索框

exports.HIDE_SEARCHBAR = HIDE_SEARCHBAR;
var HIDE_SEARCHTYPE = 'HIDE_SEARCHTYPE'; // 是否隐藏搜索类型

exports.HIDE_SEARCHTYPE = HIDE_SEARCHTYPE;
var SET_SEARCHBARRADIUS = 'SET_SEARCHBARRADIUS'; // 设置搜索框圆角

exports.SET_SEARCHBARRADIUS = SET_SEARCHBARRADIUS;
var SET_SEARCHBARSIZE = 'SET_SEARCHBARSIZE'; // 设置搜索框大小

exports.SET_SEARCHBARSIZE = SET_SEARCHBARSIZE;
var SET_SEARCHBAROPACITY = 'SET_SEARCHBAROPACITY'; // 设置搜索框透明度

exports.SET_SEARCHBAROPACITY = SET_SEARCHBAROPACITY;
var SET_FONTSIZE = 'SET_FONTSIZE'; // 设置字体大小

exports.SET_FONTSIZE = SET_FONTSIZE;
var SET_FONTCOLOR = 'SET_FONTCOLOR'; // 设置字体颜色

exports.SET_FONTCOLOR = SET_FONTCOLOR;
var RESET_ALL = 'RESET_ALL'; // 恢复默认设置
// wallPaper 相关mutations

exports.RESET_ALL = RESET_ALL;
var SET_WALLPAPERLOADING = 'SET_WALLPAPERLOADING'; // 设置壁纸加载状态

exports.SET_WALLPAPERLOADING = SET_WALLPAPERLOADING;
var SET_WALLPAPER = 'SET_WALLPAPER'; // 设置壁纸加载状态
//搜索引擎 相关的mutation

exports.SET_WALLPAPER = SET_WALLPAPER;
var DELETE_CHOOSE_ENGINE = 'DELETE_CHOOSE_ENGINE'; // 删除已选中的搜索引擎

exports.DELETE_CHOOSE_ENGINE = DELETE_CHOOSE_ENGINE;
var ADD_CHOOSE_ENGINE = 'ADD_CHOOSE_ENGINE'; // 添加已有的搜索引擎

exports.ADD_CHOOSE_ENGINE = ADD_CHOOSE_ENGINE;
var OPEN_ENGINE_POPOVER = 'OPEN_ENGINE_POPOVER'; // 打开搜索引擎弹出框

exports.OPEN_ENGINE_POPOVER = OPEN_ENGINE_POPOVER;
var CLOSE_ENGINE_POPOVER = 'CLOSE_ENGINE_POPOVER'; // 关闭搜索引擎弹出框

exports.CLOSE_ENGINE_POPOVER = CLOSE_ENGINE_POPOVER;
var CHANGE_CURRENT_ENGINE = 'CHANGE_CURRENT_ENGINE'; // 修改当前搜索引擎

exports.CHANGE_CURRENT_ENGINE = CHANGE_CURRENT_ENGINE;
var ADD_CUSTOM_ENGINE = 'ADD_CUSTOM_ENGINE'; // 添加自定义搜索引擎

exports.ADD_CUSTOM_ENGINE = ADD_CUSTOM_ENGINE;
var DELETE_CUSTOME_ENGINE = 'DELETE_CUSTOME_ENGINE'; // 删除自定义搜索引擎

exports.DELETE_CUSTOME_ENGINE = DELETE_CUSTOME_ENGINE;
var OPEN_CUSTOM_ENGINE = 'OPEN_CUSTOM_ENGINE'; // 打开自定义搜索引擎

exports.OPEN_CUSTOM_ENGINE = OPEN_CUSTOM_ENGINE;
var CLOSE_CUSTOM_ENGINE = 'CLOSE_CUSTOM_ENGINE'; // 关闭自定义搜索引擎
// 在主页添加站点相关的mutation

exports.CLOSE_CUSTOM_ENGINE = CLOSE_CUSTOM_ENGINE;
var ADD_ONE_SITE = 'ADD_ONE_SITE'; // 在主页添加一个站点

exports.ADD_ONE_SITE = ADD_ONE_SITE;
var DELETE_ONE_SITE = 'DELETE_ONE_SITE'; // 在主页删除一个站点

exports.DELETE_ONE_SITE = DELETE_ONE_SITE;
var AFTER_CHANGE = 'AFTER_CHANGE'; // 当主页添加网站内容更新时

exports.AFTER_CHANGE = AFTER_CHANGE;
var DIS_AUTO_LOAD = 'DIS_AUTO_LOAD'; // 控制是否禁用自动获取更多网站

exports.DIS_AUTO_LOAD = DIS_AUTO_LOAD;
var SET_LOADING = 'SET_LOADING'; // 设置加载动画
// 编辑网页信息 相关的mutation

exports.SET_LOADING = SET_LOADING;
var CHANGE_IS_EDIT = 'CHANGE_IS_EDIT'; // 修改编辑状态

exports.CHANGE_IS_EDIT = CHANGE_IS_EDIT;
var EDIT_DRAWER_VISIBLE = 'EDIT_DRAWER_VISIBLE'; //修改编辑弹出框的显示

exports.EDIT_DRAWER_VISIBLE = EDIT_DRAWER_VISIBLE;
var CHANGE_WEB_INFO = 'CHANGE_WEB_INFO'; //修改网站信息

exports.CHANGE_WEB_INFO = CHANGE_WEB_INFO;
var CHANGE_CURRENT_ITEM = 'CHANGE_CURRENT_ITEM'; //修改当前修改的item
// 获取网站分类 相关的mutation

exports.CHANGE_CURRENT_ITEM = CHANGE_CURRENT_ITEM;
var SET_CATEGORIES = 'SET_CATEGORIES'; // 设置网站分类

exports.SET_CATEGORIES = SET_CATEGORIES;
var SET_SITES_CATEGORY = 'SET_SITES_CATEGORY'; // 设置当前分类的网站内容

exports.SET_SITES_CATEGORY = SET_SITES_CATEGORY;
var SET_SITES_PAGE = 'SET_SITES_PAGE'; // 设置获取网站分页页码

exports.SET_SITES_PAGE = SET_SITES_PAGE;
var SET_SEARCH_SITES_VALUE = 'SET_SEARCH_SITES_VALUE'; // 设置获取网站搜索结果

exports.SET_SEARCH_SITES_VALUE = SET_SEARCH_SITES_VALUE;
var ADD_SEARCH_CATE = 'ADD_SEARCH_CATE'; // 添加搜索分类

exports.ADD_SEARCH_CATE = ADD_SEARCH_CATE;
var DELETE_SEARCH_CATE = 'DELETE_SEARCH_CATE'; // 删除搜索分类
// 主页添加网站 相关的mutation

exports.DELETE_SEARCH_CATE = DELETE_SEARCH_CATE;
var SET_HOMEMENUS = 'SET_HOMEMENUS'; // 设置主页网站

exports.SET_HOMEMENUS = SET_HOMEMENUS;